export default {
    
    INITIALIZE_TIMESHEET:'INITIALIZE_TIMESHEET',
    ADD_TIMESHEET:'ADD_TIMESHEET',
    UDPATE_TIMESHEET:'UDPATE_TIMESHEET',
    RELOAD_TIMESHEET_LIST:'RELOAD_TIMESHEET_LIST',
    
    DELETE_TIMESHEET:'DELETE_TIMESHEET',
    DELETE_TIMESHEET_DETAIL:'DELETE_TIMESHEET_DETAIL'
}